analytics: {}
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.438803
  lightness: 0.21008
  rhythmicContrast: 0.498311
  saturation: 0.690331
cta: {}
layout_spectrum: 0.403716
name: Robertlindberg.me
opengraph: {}
purpose: []
typography_spectrum: 0.795608
